# Generated by Django 4.2.8 on 2023-12-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proclog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processes',
            name='process_list',
        ),
    ]
